In [11]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import xgboost
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix
from os import listdir

import plotly.express as px
from create_data_list import *
from create_data import *
pd.set_option('display.max_rows', 500)
pd.options.plotting.backend = "plotly"

In [12]:
# path = './data/'
# dfs = []
# filenames = [path + f for f in listdir(path) if f.endswith('.csv')]
# for filename in filenames:
#     dfs.append(pd.read_csv(filename, usecols=lambda x: x not in not_read_in_file).replace(np.Inf, np.nan))

# df = pd.concat(dfs, ignore_index=True)
# df['SEG'] = 0
# dfeco = df.query('dd>=20190101 & ind_shutdown_mal==0')

In [13]:
# # high_values = df.filter(regex=r'(high|min_high)', axis=1)
# # low_values = df.filter(regex=r'(low|min_low)', axis=1)

# dfeco['enabling_hours'] =dfeco['high_part_enabling_hours']+dfeco['low_part_enabling_hours']
# dfeco['running_hours'] =dfeco['high_part_running_hours']+dfeco['low_part_running_hours']
# dfeco['load_hours'] =dfeco['high_part_load_hours']+dfeco['low_part_load_hours']
# dfeco['load_hours'] =dfeco['high_part_load_hours']+dfeco['low_part_load_hours']
# dfeco['oil_operating_hours_service'] =dfeco['high_part_oil_operating_hours_service']+dfeco['low_part_oil_operating_hours_service']
# dfeco['oil_filter_operating_hours_service'] =dfeco['high_part_oil_filter_operating_hours_service']+dfeco['low_part_oil_filter_operating_hours_service']
# dfeco['separator_filter_operating_hours_service'] =dfeco['high_part_separator_filter_operating_hours_service']+dfeco['low_part_separator_filter_operating_hours_service']
# dfeco['oil_hours_threshold_service'] =dfeco['high_part_oil_hours_threshold_service']+dfeco['low_part_oil_hours_threshold_service']
# dfeco['oil_filter_hours_threshold_service'] =dfeco['high_part_oil_filter_hours_threshold_service']+dfeco['low_part_oil_filter_hours_threshold_service']
# dfeco['separator_filter_hours_threshold_service'] =dfeco['high_part_separator_filter_hours_threshold_service']+dfeco['low_part_separator_filter_hours_threshold_service']

# dfeco['min_enabling_hours_10M'] =dfeco['min_high_part_enabling_hours_10M']+dfeco['min_low_part_enabling_hours_10M']
# dfeco['min_running_hours_10M'] =dfeco['min_high_part_running_hours_10M']+dfeco['min_low_part_running_hours_10M']
# dfeco['min_load_hours_10M'] =dfeco['min_high_part_load_hours_10M']+dfeco['min_low_part_load_hours_10M']
# dfeco['min_load_hours_10M'] =dfeco['min_high_part_load_hours_10M']+dfeco['min_low_part_load_hours_10M']
# dfeco['min_oil_operating_hours_service_10M'] =dfeco['min_high_part_oil_operating_hours_service_10M']+dfeco['min_low_part_oil_operating_hours_service_10M']
# dfeco['min_oil_filter_operating_hours_service_10M'] =dfeco['min_high_part_oil_filter_operating_hours_service_10M']+dfeco['min_low_part_oil_filter_operating_hours_service_10M']
# dfeco['min_separator_filter_operating_hours_service_10M'] =dfeco['min_high_part_separator_filter_operating_hours_service_10M']+dfeco['min_low_part_separator_filter_operating_hours_service_10M']
# dfeco['min_oil_hours_threshold_service_10M'] =dfeco['min_high_part_oil_hours_threshold_service_10M']+dfeco['min_low_part_oil_hours_threshold_service_10M']
# dfeco['min_oil_filter_hours_threshold_service_10M'] =dfeco['min_high_part_oil_filter_hours_threshold_service_10M']+dfeco['min_low_part_oil_filter_hours_threshold_service_10M']
# dfeco['min_separator_filter_hours_threshold_service_10M'] =dfeco['min_high_part_separator_filter_hours_threshold_service_10M']+dfeco['min_low_part_separator_filter_hours_threshold_service_10M']


# dfeco['min_enabling_hours_1H'] =dfeco['min_high_part_enabling_hours_1H']+dfeco['min_low_part_enabling_hours_1H']
# dfeco['min_running_hours_1H'] =dfeco['min_high_part_running_hours_1H']+dfeco['min_low_part_running_hours_1H']
# dfeco['min_load_hours_1H'] =dfeco['min_high_part_load_hours_1H']+dfeco['min_low_part_load_hours_1H']
# dfeco['min_load_hours_1H'] =dfeco['min_high_part_load_hours_1H']+dfeco['min_low_part_load_hours_1H']
# dfeco['min_oil_operating_hours_service_1H'] =dfeco['min_high_part_oil_operating_hours_service_1H']+dfeco['min_low_part_oil_operating_hours_service_1H']
# dfeco['min_oil_filter_operating_hours_service_1H'] =dfeco['min_high_part_oil_filter_operating_hours_service_1H']+dfeco['min_low_part_oil_filter_operating_hours_service_1H']
# dfeco['min_separator_filter_operating_hours_service_1H'] =dfeco['min_high_part_separator_filter_operating_hours_service_1H']+dfeco['min_low_part_separator_filter_operating_hours_service_1H']
# dfeco['min_oil_hours_threshold_service_1H'] =dfeco['min_high_part_oil_hours_threshold_service_1H']+dfeco['min_low_part_oil_hours_threshold_service_1H']
# dfeco['min_oil_filter_hours_threshold_service_1H'] =dfeco['min_high_part_oil_filter_hours_threshold_service_1H']+dfeco['min_low_part_oil_filter_hours_threshold_service_1H']
# dfeco['min_separator_filter_hours_threshold_service_1H'] =dfeco['min_high_part_separator_filter_hours_threshold_service_1H']+dfeco['min_low_part_separator_filter_hours_threshold_service_1H']

# dfeco.drop(drop_list_high_low,axis=1, inplace=True)
# dfeco.fillna(0, inplace=True)
# dfeco.sort_values(['device_id', 'ts'], inplace=True)

In [14]:
dfeco = read_data_file()

loaded files

In [15]:
dfeco.query('tsHour==0 & tsMinute==0').groupby('device_id').agg({'ind_shutdown_mal_3D_next':['count', 'mean', 'sum']})

          ind_shutdown_mal_3D_next
                             count      mean sum
device_id
93                             179  0.117318  21
296                            170  0.194118  33

In [16]:
# dfeco.query('device_id == 93').query('tsHour==0 & tsMinute==0').query('ind_shutdown_mal_3D_next==1').groupby('dd')['device_id'].count()

Load base XGB

In [17]:
base_clf = XGBClassifier()  # init model
base_clf.load_model('app/models/base_model.json')

In [18]:
params = {'max_depth':3, 
#                     'learning_rate':0.3, 
                    'objective':'binary:logistic', 
                    'gamma':0, 
                    'min_child_weight':0.3,
                    'max_delta_step':1,
                    'subsample':1, 
                    'colsample_bytree':0.6, 
                    'colsample_bylevel':0.6, 
#                     'reg_alpha':0, 
#                     'reg_lambda':1, 
 
                    'random_state':0, 
                    'seed':10, 
                    'n_estimators':30,
                    'missing':None,
                    'eval_metric':'rmsle'}

In [19]:
DEVICE_ID = 93
# dfeco_train, dfeco_test, y_train, y_test = split_dates(dfeco, test_pct=0.3, device_id=DEVICE_ID)

In [20]:
clf = XGBClassifier(**params)
clf.fit(dfeco_train, y_train, 
        eval_set=[(dfeco_train, y_train), (dfeco_test, y_test)], 
        xgb_model='app/models/base_model.json', 
        verbose=True, 
        early_stopping_rounds=5
       )

NameError: name 'dfeco_train' is not defined

In [ ]:
clf2 = XGBClassifier(**params)
clf2.n_estimators =10
clf2.fit(dfeco_train, y_train, 
        eval_set=[(dfeco_train, y_train), (dfeco_test, y_test)], 
        xgb_model='app/models/base_model.json', 
        verbose=True,
       )

In [23]:
DEVICE_ID

93

In [21]:
tmp_df = dfeco.query('device_id == @DEVICE_ID').sort_values('ts')

X = tmp_df.drop(non_model_drops, axis=1)
y = tmp_df['ind_shutdown_mal_3D_next']

dfeco_train, dfeco_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [22]:
clf3 = XGBClassifier(**params)
clf3.n_estimators =10
clf3.fit(dfeco_train, y_train, 
        eval_set=[(dfeco_train, y_train), (dfeco_test, y_test)], 
        xgb_model='app/models/base_model.json', 
        verbose=True,
       )

display(asses_raking(base_clf, y_test, dfeco_test, dfeco.query('device_id == @DEVICE_ID')))
# display(asses_raking(clf2, y_test, dfeco_test, dfeco.query('device_id == @DEVICE_ID')))
display(asses_raking(clf3, y_test, dfeco_test, dfeco.query('device_id == @DEVICE_ID')))

[0]	validation_0-rmsle:0.21960	validation_1-rmsle:0.22053
[1]	validation_0-rmsle:0.21339	validation_1-rmsle:0.21432
[2]	validation_0-rmsle:0.20682	validation_1-rmsle:0.20777
[3]	validation_0-rmsle:0.20030	validation_1-rmsle:0.20125
[4]	validation_0-rmsle:0.19319	validation_1-rmsle:0.19405
[5]	validation_0-rmsle:0.18283	validation_1-rmsle:0.18379
[6]	validation_0-rmsle:0.17436	validation_1-rmsle:0.17525
[7]	validation_0-rmsle:0.16265	validation_1-rmsle:0.16358
[8]	validation_0-rmsle:0.15205	validation_1-rmsle:0.15296
[9]	validation_0-rmsle:0.14116	validation_1-rmsle:0.14212

  rank_pct      prob ind_shutdown_mal_3D_next
                mean                    count sum      mean cumsum cumsumpct
0        0  0.004485                        9   1  0.111111      1  0.111111
1        1  0.006592                        8   0  0.000000      1  0.111111
2        2  0.012532                        9   1  0.111111      2  0.222222
3        3  0.029349                        8   0  0.000000      2  0.222222
4        4  0.041754                        9   0  0.000000      2  0.222222
5        5  0.048260                        8   0  0.000000      2  0.222222
6        6  0.056636                        8   2  0.250000      4  0.444444
7        7  0.071020                        9   2  0.222222      6  0.666667
8        8  0.081917                        8   1  0.125000      7  0.777778
9        9  0.206227                        9   2  0.222222      9  1.000000

  rank_pct      prob ind_shutdown_mal_3D_next
                mean                    count sum      mean cumsum cumsumpct
0        0  0.001564                        9   0  0.000000      0  0.000000
1        1  0.004644                        8   0  0.000000      0  0.000000
2        2  0.007667                        9   0  0.000000      0  0.000000
3        3  0.012948                        8   0  0.000000      0  0.000000
4        4  0.019063                        9   0  0.000000      0  0.000000
5        5  0.028160                        8   0  0.000000      0  0.000000
6        6  0.032337                        8   0  0.000000      0  0.000000
7        7  0.070770                        9   1  0.111111      1  0.111111
8        8  0.147061                        8   1  0.125000      2  0.222222
9        9  0.510666                        9   7  0.777778      9  1.000000

In [ ]:
asses_raking2(base_clf, y_test, dfeco_test, dfeco.query('device_id == @DEVICE_ID')

In [ ]:
DEVICE_ID = 296
dfeco_train, dfeco_test, y_train, y_test = split_dates(dfeco, test_pct=0.4, device_id=DEVICE_ID)

In [ ]:
# params = {'max_depth':3, 
# #                     'learning_rate':0.3, 
#                     'objective':'binary:logistic', 
#                     'gamma':0, 
#                     'min_child_weight':0.3,
#                     'max_delta_step':1,
#                     'subsample':1, 
#                     'colsample_bytree':0.6, 
#                     'colsample_bylevel':0.6, 
# #                     'reg_alpha':0, 
# #                     'reg_lambda':1, 
 
#                     'random_state':0, 
#                     'seed':10, 
#                     'n_estimators':30,
#                     'missing':None,
#                     'eval_metric':'logloss'}


clf = XGBClassifier(**params)
clf.fit(dfeco_train, y_train, 
        eval_set=[(dfeco_train, y_train), (dfeco_test, y_test)], 
        xgb_model='app/models/base_model.json', 
        verbose=True, 
        callbacks =[xgboost.callback.print_evaluation(period=1, show_stdv=True)],
        early_stopping_rounds=3
       )

clf2 = XGBClassifier(**params)
clf2.n_estimators =10
clf2.fit(dfeco_train, y_train, 
        eval_set=[(dfeco_train, y_train), (dfeco_test, y_test)], 
        xgb_model='app/models/base_model.json', 
        verbose=True, 
#          eval_metric=EVAL_METRIC,
       )
display(asses_raking(base_clf, y_test, dfeco_test, dfeco.query('device_id == @DEVICE_ID')))
display(asses_raking(clf2, y_test, dfeco_test, dfeco.query('device_id == @DEVICE_ID')))

In [35]:
DEVICE_ID = 296
tmp_df = dfeco.query('device_id == @DEVICE_ID').sort_values('ts')

X = tmp_df.drop(non_model_drops, axis=1)
y = tmp_df['ind_shutdown_mal_3D_next']

dfeco_train, dfeco_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [40]:
# params = {'max_depth':3, 
# #                     'learning_rate':0.3, 
#                     'objective':'binary:logistic', 
#                     'gamma':0, 
#                     'min_child_weight':0.3,
#                     'max_delta_step':1,
#                     'subsample':1, 
#                     'colsample_bytree':0.6, 
#                     'colsample_bylevel':0.6, 
# #                     'reg_alpha':0, 
# #                     'reg_lambda':1, 
 
#                     'random_state':0, 
#                     'seed':10, 
#                     'n_estimators':30,
#                     'missing':None,
#                     'eval_metric':'logloss'}

# clf = XGBClassifier(**params)
# clf.n_estimators =10
# clf.fit(dfeco_train, y_train, 
#         eval_set=[(dfeco_train, y_train), (dfeco_test, y_test)], 
#         xgb_model='app/models/base_model.json', 
#         verbose=True, 
# #          eval_metric=EVAL_METRIC,
#        )
display(asses_raking2(base_clf, y_test, dfeco_test, dfeco.query('device_id == @DEVICE_ID')))
display(asses_raking2(clf, y_test, dfeco_test, dfeco.query('device_id == @DEVICE_ID')))

  rank_pct      prob ind_shutdown_mal_3D_next
                mean                    count sum      mean cumsum cumsumpct
0        0  0.004257                        6   0  0.000000      0  0.000000
1        1  0.025923                        5   1  0.200000      1  0.090909
2        2  0.108471                        5   2  0.400000      3  0.272727
3        3  0.127661                        5   0  0.000000      3  0.272727
4        4  0.187128                        5   0  0.000000      3  0.272727
5        5  0.217795                        5   3  0.600000      6  0.545455
6        6  0.243282                        5   3  0.600000      9  0.818182
7        7  0.261618                        5   0  0.000000      9  0.818182
8        8  0.286702                        5   1  0.200000     10  0.909091
9        9  0.383686                        6   1  0.166667     11  1.000000

  rank_pct      prob ind_shutdown_mal_3D_next
                mean                    count sum      mean cumsum cumsumpct
0        0  0.011750                        6   0  0.000000      0  0.000000
1        1  0.035749                        5   0  0.000000      0  0.000000
2        2  0.048234                        5   0  0.000000      0  0.000000
3        3  0.069157                        5   0  0.000000      0  0.000000
4        4  0.085519                        5   0  0.000000      0  0.000000
5        5  0.100365                        5   0  0.000000      0  0.000000
6        6  0.187317                        5   0  0.000000      0  0.000000
7        7  0.297602                        5   3  0.600000      3  0.272727
8        8  0.419908                        5   3  0.600000      6  0.545455
9        9  0.542945                        6   5  0.833333     11  1.000000

In [39]:

def asses_raking2(clf, y, X, df):
    tmp = pd.DataFrame(y)
    tmp['prob'] = clf.predict_proba(X)[:, 1]
    tmp['pct'] = pd.qcut(tmp['prob'], 10, labels=False, duplicates='drop')
    tmp = tmp.loc[(df.tsHour == 0) & (df.tsMinute == 0), :]
    tmp['rank'] = tmp['prob'].rank(method='first', ascending=1)
    tmp['rank_pct'] = pd.qcut(tmp['rank'], 10, labels=False, duplicates='drop' )

    tmp2 = tmp.query('rank_pct>=0').groupby('rank_pct', as_index=False).agg(
        {'prob': 'mean', 'ind_shutdown_mal_3D_next': ['count', 'sum', 'mean']})
    tmp2[('ind_shutdown_mal_3D_next', 'cumsum')] = tmp2[('ind_shutdown_mal_3D_next', 'sum')].cumsum()
    tmp2[('ind_shutdown_mal_3D_next', 'cumsumpct')] = tmp2[('ind_shutdown_mal_3D_next', 'cumsum')] / tmp2[
        ('ind_shutdown_mal_3D_next', 'sum')].sum()
    return tmp2

In [ ]:
tmp = pd.DataFrame(y_test)
tmp['prob'] = clf.predict_proba(dfeco_test)[:, 1]
tmp = tmp.loc[(dfeco.tsHour == 0) & (dfeco.tsMinute == 0), :]
tmp.sort_values('prob', ascending=False)
tmp.head(int(0.2*(len(tmp))))['ind_shutdown_mal_3D_next'].sum() / tmp['ind_shutdown_mal_3D_next'].sum()

In [ ]:
tmp.head(int(0.2*(len(tmp))))['ind_shutdown_mal_3D_next'].sum()